name: Create test report

on: [push, pull_request]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test:ci
    - name: Test Report
      uses: dorny/test-reporter@v1.8.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: junit.xml             # Path to test results
        reporter: jest-junit        # Format of test results
